### PR TITLE
FIX : When set value to Blackboard while it contains the value with null

### PR DESCRIPTION
**Pull request by MohHeader**
if a key has a value of ( null )
then if tried to update it, will through NullException.

### CODE REVIEW

**Comment by meniku** [comment]
Thanks a lot

**Comment by meniku** [comment]
I fixed another thing: When you set the value to null on a key that's already contained a value of null:

https://github.com/meniku/NPBehave/commit/0d99bede629850ba65e38294708dde878d2e8e7e#diff-1bd54b8aa6986381faf0e0744ad78638L89

**Comment by MohHeader** [comment]
Perfect, Thanks for your prompt action.
👍 

Currently I am using NPBehave in our next Game,
I think I have a lot of questions and comments, ( to come later ;) ) 

Also I was thinking if you can provide this Library on Unity Assets Store.
I think that would make it more easier to find ( I found it by chance after a lot of searching )

And super thanks for your effort

**Comment by meniku** [comment]
Thanks, I'm glad that it's useful for you. I would love to improve this library so any feedback is always welcome :)

I submitted the library to the Unity Asset Store yesterday. It can take up to 10 days until it shows up though ( if they are fine with it ). 

If you don't mind you could show me your game once it's in a presentable state? :)

**Comment by MohHeader** [comment]
Cool, hope that it goes well with the Unity Store,

For the game, Unfortunately I think it would take some time to be in a presentable state, Due to ( Company policies ).
But will make sure to update you once we have something ready ;) 

Thanks once again 👍

**Pull request merged**
